Repository Huawei-CPLLab/PyDSL, pull requests merged in 2025-08, with the labels that each got.

#81 fix #66: implement cast from Int -> Index
  src/pydsl/type.py
  tests/e2e/test_arith.py
Labels: feature, small

#77 Add templates to PyDSL
  src/pydsl/frontend.py
  tests/e2e/test_templates.py
Labels: feature

#75 Improve build instructions for developers
  dev/build.md
  dev/dev_docs.md
Labels: documentation, small

#72 Use correct scope for inline functions
  dev/dev_docs.md
  src/pydsl/func.py
  tests/e2e/test_func.py
Labels: bug, small

#82 Tensor empty and full, new alloc syntax and memory spaces
  src/pydsl/compiler.py
  src/pydsl/func.py
  src/pydsl/gpu.py
  src/pydsl/linalg.py
  src/pydsl/memref.py
  src/pydsl/protocols.py
  src/pydsl/tensor.py
  src/pydsl/type.py
  src/pydsl/vector.py
  tests/e2e/test_algorithms.py
  tests/e2e/test_linalg.py
  tests/e2e/test_memref.py
  tests/e2e/test_tensor.py
  tests/unit/test_protocols.py
Labels: feature
